# Generated by Django 5.1.4 on 2025-01-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_price_product_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='price',
        ),
    ]
